controller_list:
  - name: /xarm/xarm5_traj_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
  - name: /DASHGO/gripper_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - Rev1Servo
  - name: /DASHGO/head_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - Cam1Rev1
      - Cam1Rev2
  - name: /DASHGO/base_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - odom_x
      - odom_y
      - odom_r
